version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_USER: rootuser
      MYSQL_ROOT_HOST: "%"
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
